Compile all language support in one python file
NJACKWinterOfCode/HackerRank-Test-Case-Generator pull request #8
Opened 2018-12-03 13:51 UTC by agarwalrounak

### Checklist:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you successfully ran tests with your changes locally?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Issues Solved

Fixes #3 

### Changes:
- Compiled all language support in one python file(for both Python2 and Python3)
- Made the code PEP8 compatible
- Updated README accordingly

2018-12-03 18:57 UTC, aashutoshrathi requested changes
Check comments and test it locally.

2018-12-03 18:57 UTC, aashutoshrathi commented on Python2/Example/TCGen.py
> +if choice != '1' or choice != '2' or choice != '3' or choice != '4':
This logic is wrong, makes it:
```py
if choice != '1' and choice != '2' and choice != '3' and choice != '4':
```

2018-12-03 18:57 UTC, aashutoshrathi commented on Python2/Example/TCGen.py
> +choice = raw_input("Enter your choice of language\n1 for C\n2 for C++\n3 for Java\n4 for Python")
Add "\n" at the end once more.

2018-12-03 18:57 UTC, aashutoshrathi commented on Python2/TC-Generator/TCGen.py
> +if choice != '1' or choice != '2' or choice != '3' or choice != '4':
Same changes here too.

2018-12-04 07:49 UTC, agarwalrounak commented
Done. Please review.

2018-12-04 08:28 UTC, aashutoshrathi reviewed
Yeah, that thing works fine now.
Make choice field an integer only.

2018-12-04 10:20 UTC, agarwalrounak commented
@aashutoshrathi done, please review.

2018-12-04 11:12 UTC, aashutoshrathi approved these changes
LGTM Great work.

2018-12-04 12:47 UTC, agarwalrounak commented
Thanks! Please merge the PR.

2018-12-04 13:17 UTC, merged